### ISSUE TITLE
Replace Vagrant local dev setup with Docker

### ISSUE THREAD

**Issue by sbine** [sbine/bdgt#22]
I don't use the Vagrant setup anymore and suspect the project would be easier to contribute to if it were replaced with a Docker compose config.

See [vagrant.sh](https://github.com/sbine/bdgt/blob/master/vagrant.sh)

**Comment by pfaffenrodt** [comment]
@sbine There are many solutions out there.

* https://laradock.io/ could be used aside 
* https://ddev.readthedocs.io/en/stable/users/cli-usage/#laravel-quickstart cli tool
* https://github.com/sinnbeck/laravel-served integrated into artisan. but you need php to boot it up
* or own docker-compose.yml what you would maintain
* and so on

Do you want to maintain Dockerfile?

**Comment by sbine** [comment]
@pfaffenrodt yes, ideally I'd like a self-contained `docker-compose.yml` file in the repo as a drop-in replacement for `vagrant.sh` and wouldn't mind maintaining it.

I'm happy with my current local dev setup of Laravel Valet + Docker for MySQL, but this would be targeted at people who don't have existing PHP/MySQL infrastructure configured (and I'd probably start using it).

I suspect bdgt could get away with vanilla Docker configs rather than something as batteries-included as Laradock, since it's using a tiny subset of supported software, but I'm open to suggestions.

**Comment by mralanlee** [comment]
I'd like to take a stab at this but I'd like to understand your main requirements. 

Essentially, I believe you want to setup an environment so that all dependencies can be containerized within docker-compose (i.e. mysql and php), while things like node.js should be available on the host device right?

**Comment by sbine** [comment]
@mralanlee that's right. It would be great if each dependency was in its own container, and I think I'd even prefer if NPM were containerized too (but that's less important and can be a future enhancement).

For the initial versions we could mimic bdgt's current production environment: PHP 7.3, Apache 2.4, and MariaDB 10.1. Nginx and/or plain MySQL would be OK too if that's easier.

Thanks! Let me know if you have any other questions.

**Comment by mralanlee** [comment]
Sounds good, let me kick off a PR to get the basic requirements setup and it can be iterated and updated to simplify setting up a dev environment.

**Comment by pfaffenrodt** [comment]
@mralanlee
 See requirements here: https://laravel.com/docs/8.x/installation#server-requirements

**Comment by PPastene** [comment]
I was looking into vagrant.sh and it's not so hard to write a basic Dockerfile along with a docker-compose.yml. Depending of which services must be configured and which ones can be automated. I.E you can have a Dockerfile that comes with PHP, composer, and NodeJS that only works as JS compiler if you work with React or Vue, while the docker-compose.yml can be used to start the Mysql and Apache/Nginx services along with the container generated by the Dockerfile, also we can create a volume to use as persistence between the project and the container so you don't copy anything and you can make changes on the fly. Also, there's from for some improvement, instead of using Ubuntu you can use Alpine to save space

I will fork your project and make a Dockerfile + docker-compose.yml with persistence

**Comment by mralanlee** [comment]
@pfaffenrodt thanks! I'll take a look.

@PPastene I have a draft PR open and would be happen to work on this together.

**Comment by sbine** [comment]
This is fixed with contributions from #48, #25, and #58, and I welcome PRs for any further improvements. Thanks all 🎃
