### ISSUE TITLE
All categories page does not work when single category budget is set to $0

### ISSUE THREAD

**Issue by ActuallyConnor** [sbine/bdgt#39]
When the budget is set to $0 for a category and then you try to go to the list of all the categories it errors out. If you go back to that individual category and set the value to a positive number it no longer errors out.

![bdgt](https://user-images.githubusercontent.com/20844837/95024008-65332b00-064e-11eb-90b2-e1eee7f7c4cf.gif)

**Comment by pfaffenrodt** [comment]
I take a look

**Comment by Saibamen** [comment]
Pleace copy and paste here stack trace

**Comment by pfaffenrodt** [comment]
I fixed the calculation. Maybe it would be better, not even to allow to create or update a budget to a value below or equal of zero

**Comment by sbine** [comment]
Fixed in #43, thanks! I'm OK with allowing category budgets of 0 since you might want to skip budgeting for a month or two but not delete the category.

The budgeting feature in bdgt needs an overhaul anyway, I have a prototype implemented at `/budget` but don't yet have a good plan to integrate it into the rest of the UI.
